# Generated by Django 4.2.3 on 2023-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_customuser_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
    ]
