# Generated by Django 4.2.3 on 2023-07-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0002_customer_course_grade_course_course_code_and_more"),
        ("users", "0003_customuser_is_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="courses",
            field=models.ManyToManyField(to="program.course"),
        ),
    ]
