# Generated by Django 4.2.3 on 2023-07-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="Grade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="credit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="gpa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
