# Generated by Django 4.2.3 on 2023-07-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("verify_code", models.CharField(max_length=100)),
                ("ref_code", models.CharField(blank=True, max_length=6, null=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("dob", models.DateField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wassce", "wassce"),
                            ("degree", "degree"),
                            ("masters", "masters"),
                            ("doctorate", "doctorate"),
                            ("professor", "professor"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_lecturer", models.BooleanField(default=False)),
                ("is_hod", models.BooleanField(default=False)),
                ("is_student", models.BooleanField(default=False)),
                (
                    "is_course_registered",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("is_staff", models.BooleanField(blank=True, default=False, null=True)),
                ("is_fee", models.BooleanField(blank=True, default=False, null=True)),
                ("is_admin", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "is_verified",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="program.program",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
                "ordering": ["-id"],
            },
        ),
    ]
