# Generated by Django 4.2.3 on 2023-07-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Semester 1", "Semester 1"),
                            ("Semester 2", "Semester 2"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("credit", models.IntegerField(blank=True, null=True)),
                ("Grade", models.CharField(blank=True, max_length=100, null=True)),
                ("mark", models.CharField(blank=True, max_length=100, null=True)),
                ("gpa", models.CharField(blank=True, max_length=100, null=True)),
                ("course_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Not Registered", max_length=100, null=True
                    ),
                ),
                ("date_registered", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                            ("Graduant", "Graduant"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.department",
                    ),
                ),
            ],
        ),
    ]
