# Generated by Django 4.2.3 on 2023-07-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
