# Generated by Django 4.2.3 on 2023-07-23 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0004_sharedfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sharedfile",
            old_name="file",
            new_name="file_name",
        ),
    ]
