# Generated by Django 4.2.3 on 2023-07-21 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_booker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="day_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.availabletime",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="reserver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_reserver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="day_and_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointment.daytime"
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
