# Generated by Django 4.2.3 on 2023-07-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[("MOMO", "MOMO"), ("CARD", "CARD")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Visa Card", "Visa Card"),
                            ("Master Card", "Master Card"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "momo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN", "MTN"),
                            ("VODAFONE", "VODAFONE"),
                            ("AIRTELTIGO", "AIRTELTIGO"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("price", models.FloatField(default=0.0)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0.0)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fees.payment",
                    ),
                ),
            ],
        ),
    ]
